apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/base
  - steam-companion/steam-companion-sealed.yaml
patchesStrategicMerge:
  - steam-companion/steam-companion.yaml
