apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/base
  - smart-news/smart-news-sealed.yaml
  - steam-companion/steam-companion-sealed.yaml
patchesStrategicMerge:
  - smart-news/smart-news.yaml
  - steam-companion/steam-companion.yaml
