apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-crds
  namespace: flux-system
spec:
  interval: 10m
  path: "./flux/infrastructure/base/cert-manager"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-cluster-issuer
  namespace: apps
spec:
  interval: 10m
  path: "./flux/infrastructure/staging/cert-manager"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: cert-manager-crds
      namespace: flux-system
  healthChecks:
    - kind: Deployment
      name: cert-manager-webhook
      namespace: apps
